"""setup user & workflow relationship

Revision ID: 88090d5d3168
Revises: e2a1ec48da3b
Create Date: 2024-09-27 20:53:05.995582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88090d5d3168'
down_revision: Union[str, None] = 'e2a1ec48da3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.add_column('workflow', sa.Column('updated_by', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'workflow', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'workflow', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'updated_by')
    op.drop_column('workflow', 'created_by')
    # ### end Alembic commands ###
