"""revised

Revision ID: 8b8cd1e18e33
Revises: c499e0ea5e38
Create Date: 2024-10-02 22:30:15.220431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b8cd1e18e33'
down_revision: Union[str, None] = 'c499e0ea5e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflow_updated_by_fkey', 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('workflow_updated_by_fkey', 'workflow', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###
