"""intent model

Revision ID: abf641b5a007
Revises: 59f5414e7497
Create Date: 2024-09-27 18:38:18.252040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abf641b5a007'
down_revision: Union[str, None] = '59f5414e7497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'nodes')
    op.drop_column('workflow', 'edges')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('edges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workflow', sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
